import { Question, UserProgressItem, UserStoreState } from '../types';
import { User } from '../types/auth';

// Export questions formatted for 1-click Anki Deck Import (.csv)
export const exportToAnkiCSV = (
  questions: Question[],
  progress: Record<string, UserProgressItem>,
  deckName: string = 'Cheat_Code_Active_Recall'
) => {
  const headers = ['Front', 'Back', 'Tags'];
  const rows: string[] = [];

  questions.forEach((q) => {
    const prog = progress[String(q.id)];
    const status = prog?.status || 'todo';
    const notes = prog?.notes ? `<br><br><b>Personal Notes:</b> ${prog.notes}` : '';

    // Front: Problem info and prompt
    const front = `
      <div style="font-family:monospace; text-align:center; background:#0a0a0a; color:#f0f0f0; padding:12px; border:1px solid #2a2a2a;">
        <span style="font-size:12px; font-weight:bold; color:#FFFF00;">#${q.id}</span>
        <h2 style="margin:6px 0 10px 0; color:#f0f0f0;">${q.title}</h2>
        <span style="font-size:11px; padding:2px 6px; border:1px solid #FFFF00; color:#FFFF00; font-weight:bold;">
          [${q.difficulty.toUpperCase()}]
        </span>
        <div style="margin-top:14px; font-size:13px; color:#a0a0a0;">
          <b>Prompt:</b> What is the optimal algorithmic paradigm, invariant, and time/space complexity?
        </div>
      </div>
    `.trim().replace(/\n/g, ' ').replace(/"/g, '""');

    // Back: Solution guidance and prompt
    const back = `
      <div style="font-family:monospace; background:#0a0a0a; color:#f0f0f0; padding:12px; border:1px solid #2a2a2a;">
        <h3 style="color:#FFFF00; margin-top:0;">[OPTIMAL_APPROACH_INVARIANT]</h3>
        <p style="font-size:13px; color:#a0a0a0;">Review optimal C++ approach and invariant in Cheat Code.</p>
        <p style="font-size:12px; color:#FFFF00;">LeetCode URL: <a style="color:#FFFF00;" href="${q.url}">${q.url}</a></p>
        ${notes}
      </div>
    `.trim().replace(/\n/g, ' ').replace(/"/g, '""');

    const topicsTag = q.topics.slice(0, 3).map(t => t.toLowerCase().replace(/\s+/g, '-')).join(' ');
    const tags = `leetcode difficulty_${q.difficulty} status_${status} ${topicsTag}`;

    rows.push(`"${front}","${back}","${tags}"`);
  });

  const csvContent = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${deckName}_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};

// Export to Obsidian / Notion Markdown Notes (.md)
export const exportToObsidianMarkdown = (
  questions: Question[],
  progress: Record<string, UserProgressItem>,
  user: User
) => {
  const solvedQuestions = questions.filter(q => {
    const s = progress[String(q.id)]?.status;
    return s === 'solved' || s === 'mastered' || s === 'review';
  });

  const lines: string[] = [];
  lines.push(`# 📚 LeetCode Interview Study Compendium`);
  lines.push(`> Generated by **Cheat Code SaaS** for **${user.name}** (${user.tier.toUpperCase()})`);
  lines.push(`> Date: ${new Date().toLocaleDateString()} • Target Company: ${user.targetCompany || 'FAANG'}`);
  lines.push(`> Total Documented Solves: ${solvedQuestions.length} questions\n`);
  lines.push(`---`);

  solvedQuestions.forEach((q, idx) => {
    const p = progress[String(q.id)];
    lines.push(`\n## ${idx + 1}. [#${q.id} - ${q.title}](${q.url})`);
    lines.push(`- **Difficulty**: \`${q.difficulty}\` | **Status**: \`${p?.status?.toUpperCase() || 'SOLVED'}\``);
    lines.push(`- **Topics**: ${q.topics.join(', ')}`);
    if (p?.tags && p.tags.length > 0) {
      lines.push(`- **Tags**: ${p.tags.map(t => `\`#${t}\``).join(' ')}`);
    }
    if (p?.notes) {
      lines.push(`\n### 📝 Personal Notes & Invariants`);
      lines.push(p.notes);
    }
    if (p?.codeSnippet?.code) {
      lines.push(`\n\`\`\`cpp\n${p.codeSnippet.code}\n\`\`\``);
    }
    lines.push(`\n---`);
  });

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `LeetCode_Notes_${user.targetCompany || 'FAANG'}_${new Date().toISOString().split('T')[0]}.md`);
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};
